jwt:
  signingMethod: HS512
redis:
  addr: 47.100.7.136:10379
  password: MNBV7QCvX9YX&UK8
  db: 15
  poolSize: 100
logger:
  dir: logs
  maxSize: 50
  maxBackups: 30
  maxAge: 30
  console: true
  json: true
  loggers:
    ws:
      file: ws.log
    inbox:
      file: inbox.log
