jwt:
  signingMethod: HS512
redis:
  addr: 192.168.1.2:6379
  password: none
  db: 0
  poolSize: 100
logger:
  dir: logs
  maxSize: 50
  maxBackups: 30
  maxAge: 30
  console: true
  json: true
  loggers:
    ws:
      file: ws.log
