jwt:
  signingMethod: HS512
redis:
  addr: 59.110.7.76:6600
  password: MNBV7QCvX9YX&UK8xu
  db: 0
  poolSize: 100
logger:
  dir: logs
  maxSize: 50
  maxBackups: 30
  maxAge: 30
  console: true
  json: true
  loggers:
    ws:
      file: ws.log
    inbox:
      file: inbox.log
